app:
  name: "@project.artifactId@"
  version: "@project.version@"

logging:
  level:
    ROOT: "info"
    org.springframework: "info"
    net.playground.productsbackend: "info"

server:
  servlet:
    context-path: "/product-service"

# for actuator endpoints (spring boot 2)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: "/var/log/product-service/application.log"
